#!/bin/sh
# Strip Co-Authored-By trailers from commit messages
sed -i.bak '/^[Cc][Oo]-[Aa][Uu][Tt][Hh][Oo][Rr][Ee][Dd]-[Bb][Yy]:/d' "$1"
# Remove trailing blank lines left behind
sed -i.bak -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$1"
rm -f "$1.bak"
